@echo off
cd %2
%1 -i silent -DCHOSEN_INSTALL_SET="Complete" -DUSER_INSTALL_DIR="%3" -DIESD_INSTALL_DBTYPE_POSTGRESEMBEDDED=1 -DIESD_INSTALL_EMPTY_DATABASE=1 -DUSER_SHORTCUTS="C:\MentorGraphics\Shortcuts"~ -DenablePEP=true -DenableSelfSignedCertificates=true -DCIS_MODE=Both -DCIS_CERTIFICATE_PATH= -DCIS_CERTIFICATE_PWD= -DCIS_KEYSTORE_PATH= -DCIS_KEYSTORE_PWD=
